name: Backend CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ vars.IMAGE_NAMESPACE || github.repository_owner }}/pmt-backend

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Build & test
        run: ./mvnw -B -Dspring.profiles.active=test -DskipTests=false test

      - name: Generate JaCoCo report (XML + HTML)
        run: ./mvnw -B -Dspring.profiles.active=test -DskipTests=false test jacoco:report

      - name: Tests Summary (JUnit)
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          check_name: "JUnit Test Results"
          detailed_summary: true
          include_passed: true
          require_tests: true

      - name: Coverage Summary (JaCoCo)
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: '**/target/site/jacoco/jacoco.xml'
          badge: true
          format: 'markdown'
          output: 'both'
          hide_complexity: true
          indicators: true
          thresholds: '55 60'

      - name: Enforce minimum coverage (60%)
        run: |
          xml=$(cat target/site/jacoco/jacoco.xml)
          missed=$(echo "$xml" | grep -o 'type="LINE"[^>]*/>' | \
                   sed -E 's/.*missed="([0-9]+)".*covered="([0-9]+)".*/\1 \2/' | \
                   awk '{m+=$1;c+=$2} END {print m, c}')
          m=$(echo $missed | awk '{print $1}'); c=$(echo $missed | awk '{print $2}')
          total=$((m+c))
          cov=$(( 100*(c) / (total==0?1:total) ))
          echo "Line coverage = ${cov}% (covered=${c}, missed=${m}, total=${total})" >> $GITHUB_STEP_SUMMARY
          if [ "$cov" -lt 60 ]; then
            echo "Cov < 60% => fail"; exit 1
          fi

      - name: Upload JaCoCo HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-html
          path: target/site/jacoco/


      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          echo "sha_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "version_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.sha_tag }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

      - name: Tag & push version (if tag)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker pull ${{ env.IMAGE_NAME }}:latest
          docker tag  ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version_tag }}
          docker push ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version_tag }}
